import { InfraccionResponseDto } from '../dto/InfraccionResponse.dto';
import { Infraccion } from '../entities/Infraccion.entity';

export const mapInfraccionToResponse = (
  infraccion: Infraccion,
): InfraccionResponseDto => {
  const primerDetalle = infraccion.detalles?.[0];

  return {
    id: infraccion.id,
    folioInfraccion: infraccion.folioInfraccion,
    fecha: infraccion.fecha,
    hora: infraccion.hora,
    fechaHora: infraccion.fechaHora,
    situacionVehiculo: infraccion.situacionVehiculo,
    estatus: infraccion.estatus,
    monto: infraccion.monto,
    encierro: infraccion.encierro,
    servicioGrua: infraccion.servicioGrua,
    claveOficial: primerDetalle?.catalogoInfraccion?.claveOficial,
    numeroParteInformativo: primerDetalle?.numeroParteInformativo,
    nombreOperativo: primerDetalle?.nombreOperativo,
    sitioServicioPublico: primerDetalle?.sitioServicioPublico,
    infractor: {
      id: infraccion.infractor.id,
      nombre: infraccion.infractor.nombre,
      genero: infraccion.infractor.genero,
      numeroLicencia: infraccion.infractor.numeroLicencia,
    },
    vehiculo: {
      id: infraccion.vehiculo.id,
      servicio: infraccion.vehiculo.servicio,
      clase: infraccion.vehiculo.clase,
      tipo: infraccion.vehiculo.tipo,
      marca: infraccion.vehiculo.marca,
      modelo: infraccion.vehiculo.modelo,
      color: infraccion.vehiculo.color,
      placas: infraccion.vehiculo.placas,
      estadoPlacas: infraccion.vehiculo.estadoPlacas,
      serie: infraccion.vehiculo.serie,
      motor: infraccion.vehiculo.motor,
    },
    ubicacion: {
      id: infraccion.ubicacion.id,
      municipio: infraccion.ubicacion.municipio,
      agencia: infraccion.ubicacion.agencia,
      colonia: infraccion.ubicacion.colonia,
      calle: infraccion.ubicacion.calle,
      m1: infraccion.ubicacion.m1,
      m2: infraccion.ubicacion.m2,
      m3: infraccion.ubicacion.m3,
      m4: infraccion.ubicacion.m4,
    },
    detalles:
      infraccion.detalles?.map((detalle) => ({
        id: detalle.id,
        claveOficial: detalle.catalogoInfraccion.claveOficial,
        numeroParteInformativo: detalle.numeroParteInformativo,
        nombreOperativo: detalle.nombreOperativo,
        sitioServicioPublico: detalle.sitioServicioPublico,
      })) ?? [],
    createdBy: {
      id: infraccion.createdBy.id,
      username: infraccion.createdBy.username,
      nombre: infraccion.createdBy.nombre,
      apellido: infraccion.createdBy.apellido,
      role: infraccion.createdBy.role,
    },
    nombreInfractor: infraccion.infractor.nombre,
    genero: infraccion.infractor.genero,
    numeroLicencia: infraccion.infractor.numeroLicencia,
    servicio: infraccion.vehiculo.servicio,
    clase: infraccion.vehiculo.clase,
    tipo: infraccion.vehiculo.tipo,
    marca: infraccion.vehiculo.marca,
    modelo: infraccion.vehiculo.modelo,
    color: infraccion.vehiculo.color,
    placas: infraccion.vehiculo.placas,
    estadoPlacas: infraccion.vehiculo.estadoPlacas,
    serie: infraccion.vehiculo.serie,
    motor: infraccion.vehiculo.motor,
    municipio: infraccion.ubicacion.municipio,
    agencia: infraccion.ubicacion.agencia,
    colonia: infraccion.ubicacion.colonia,
    calle: infraccion.ubicacion.calle,
    m1: infraccion.ubicacion.m1,
    m2: infraccion.ubicacion.m2,
    m3: infraccion.ubicacion.m3,
    m4: infraccion.ubicacion.m4,
  };
};
